[package]
name = "final_bot_x"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["rt", "rt-multi-thread", "macros"] }
serenity = "0.12.0"
serenity-commands = "0.4.0"
dotenv = "0.15.0"
